Temporary removed branch parent validation

diff --git a/.github/workflows/configure-staging.yaml b/.github/workflows/configure-staging.yaml
--- a/.github/workflows/configure-staging.yaml
+++ b/.github/workflows/configure-staging.yaml
@@ -49,33 +49,33 @@ jobs:
           PREFIX=$(echo '${{ github.ref_name }}' | cut -d '/' -f 1)
           echo $PREFIX
           echo "prefix=$PREFIX" >> $GITHUB_OUTPUT
-      -
-        name: Validate hotfix parent branch
-        if: steps.origin.outputs.prefix == 'hotfix'
-        run: |
-          git checkout ${{ github.event.repository.default_branch }}
-          git checkout ${{ github.ref_name }}
-          PARENT=$(git show-branch -a | grep '\*' | grep -v `git rev-parse --abbrev-ref HEAD` | head -n1 | sed 's/.*\[\(.*\)\].*/\1/' | sed 's/[\^~].*//')
-          echo $PARENT
-          if [ $PARENT != '${{ github.event.repository.default_branch }}' ]
-          then
-            echo "Invalid parent branch '$PARENT', should be '${{ github.event.repository.default_branch }}'"
-            exit 2
-          fi
-      -
-        name: Validate release parent branch
-        if: steps.origin.outputs.prefix == 'release'
-        run: |
-          BRANCH='develop'
-          git checkout $BRANCH
-          git checkout ${{ github.ref_name }}
-          PARENT=$(git show-branch -a | grep '\*' | grep -v `git rev-parse --abbrev-ref HEAD` | head -n1 | sed 's/.*\[\(.*\)\].*/\1/' | sed 's/[\^~].*//')
-          echo $PARENT
-          if [ $PARENT != $BRANCH ]
-          then
-            echo "Invalid parent branch '$PARENT', should be '$BRANCH'"
-            exit 3
-          fi
+      #! -
+      #!   name: Validate hotfix parent branch
+      #!   if: steps.origin.outputs.prefix == 'hotfix'
+      #!   run: |
+      #!     git checkout ${{ github.event.repository.default_branch }}
+      #!     git checkout ${{ github.ref_name }}
+      #!     PARENT=$(git show-branch -a | grep '\*' | grep -v `git rev-parse --abbrev-ref HEAD` | head -n1 | sed 's/.*\[\(.*\)\].*/\1/' | sed 's/[\^~].*//')
+      #!     echo $PARENT
+      #!     if [ $PARENT != '${{ github.event.repository.default_branch }}' ]
+      #!     then
+      #!       echo "Invalid parent branch '$PARENT', should be '${{ github.event.repository.default_branch }}'"
+      #!       exit 2
+      #!     fi
+      #! -
+      #!   name: Validate release parent branch
+      #!   if: steps.origin.outputs.prefix == 'release'
+      #!   run: |
+      #!     BRANCH='develop'
+      #!     git checkout $BRANCH
+      #!     git checkout ${{ github.ref_name }}
+      #!     PARENT=$(git show-branch -a | grep '\*' | grep -v `git rev-parse --abbrev-ref HEAD` | head -n1 | sed 's/.*\[\(.*\)\].*/\1/' | sed 's/[\^~].*//')
+      #!     echo $PARENT
+      #!     if [ $PARENT != $BRANCH ]
+      #!     then
+      #!       echo "Invalid parent branch '$PARENT', should be '$BRANCH'"
+      #!       exit 3
+      #!     fi
       - 
         name: Validate branch
         if: steps.origin.outputs.prefix == ''
@@ -102,6 +102,7 @@ jobs:
         run: |
           echo "Release with tag '${{ steps.version.outputs.version }}' already exists"
           exit 5
+      # TODO: check if hotfix or release with such version is already created
       -
         uses: Geta/gks/actions/read-config-file@actions/v2
         id: settings
